-- Roles & permissions scaffolding for sb-mono.
-- Mirrors np-mono's pattern: app_role + app_permission ENUMs, user_roles + role_permissions tables,
-- custom_access_token_hook injecting user_role JWT claim, authorize() helper for RLS.
--
-- Roles in v1: admin, free (default). pro is reserved for Phase 2 monetization (themes, branding).
-- Also installs the permission-gated INSERT/UPDATE/DELETE policies for matches/events,
-- which depend on public.authorize() defined below — so they belong in this migration, not 000.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'app_role') THEN
    CREATE TYPE public.app_role AS ENUM (
      'admin',
      'free',
      'pro'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'app_permission') THEN
    CREATE TYPE public.app_permission AS ENUM (
      'match.create',
      'match.update.own',
      'match.delete.own',
      'theme.use.free',
      'theme.use.pro',
      'branding.custom',
      'admin.users.manage_roles',
      'admin.themes.publish'
    );
  END IF;
END
$$;


CREATE TABLE IF NOT EXISTS public.user_roles (
    id        bigint generated by default as identity primary key,
    user_id   uuid references auth.users on delete cascade not null,
    role      app_role not null,
    unique (user_id, role)
);
COMMENT ON TABLE public.user_roles IS 'Application roles for each user.';

CREATE TABLE IF NOT EXISTS public.role_permissions (
    id           bigint generated by default as identity primary key,
    role         app_role not null,
    permission   app_permission not null,
    unique (role, permission)
);
COMMENT ON TABLE public.role_permissions IS 'Application permissions granted per role.';


-- Seed role → permission grants. Idempotent via ON CONFLICT.
INSERT INTO public.role_permissions (role, permission) VALUES
    ('free', 'match.create'),
    ('free', 'match.update.own'),
    ('free', 'match.delete.own'),
    ('free', 'theme.use.free'),

    ('pro',  'match.create'),
    ('pro',  'match.update.own'),
    ('pro',  'match.delete.own'),
    ('pro',  'theme.use.free'),
    ('pro',  'theme.use.pro'),
    ('pro',  'branding.custom'),

    ('admin', 'match.create'),
    ('admin', 'match.update.own'),
    ('admin', 'match.delete.own'),
    ('admin', 'theme.use.free'),
    ('admin', 'theme.use.pro'),
    ('admin', 'branding.custom'),
    ('admin', 'admin.users.manage_roles'),
    ('admin', 'admin.themes.publish')
ON CONFLICT (role, permission) DO NOTHING;


-- Custom access token hook: injects user_role into JWT claims on every token issuance.
CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SET search_path = ''
AS $$
DECLARE
    claims jsonb;
    user_role public.app_role;
BEGIN
    SELECT role INTO user_role
    FROM public.user_roles
    WHERE user_id = (event->>'user_id')::uuid
    LIMIT 1;

    claims := event->'claims';

    IF user_role IS NOT NULL THEN
        claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
    ELSE
        claims := jsonb_set(claims, '{user_role}', 'null');
    END IF;

    event := jsonb_set(event, '{claims}', claims);
    RETURN event;
END;
$$;


-- Auth admin needs read access to user_roles (the hook runs as supabase_auth_admin).
GRANT USAGE ON SCHEMA public TO supabase_auth_admin;
GRANT EXECUTE ON FUNCTION public.custom_access_token_hook TO supabase_auth_admin;
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook FROM authenticated, anon, public;

GRANT ALL ON TABLE public.user_roles TO supabase_auth_admin;
REVOKE ALL ON TABLE public.user_roles FROM authenticated, anon, public;

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "auth_admin_reads_user_roles" ON public.user_roles;
CREATE POLICY "auth_admin_reads_user_roles" ON public.user_roles
    AS PERMISSIVE FOR SELECT
    TO supabase_auth_admin
    USING (true);

-- role_permissions is RLS-enabled with a permissive SELECT for authenticated.
-- The data isn't user-specific (it's the static role→permission grant matrix),
-- but we don't want anon clients enumerating it via PostgREST either.
-- authorize() and get_my_permissions() are SECURITY DEFINER so they bypass RLS,
-- so locking the table down doesn't break those code paths.
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "role_permissions_read_authenticated" ON public.role_permissions;
CREATE POLICY "role_permissions_read_authenticated" ON public.role_permissions
    FOR SELECT
    TO authenticated
    USING (true);


-- authorize(): RLS helper. Reads user_role from JWT claim, checks role_permissions.
CREATE OR REPLACE FUNCTION public.authorize(requested_permission app_permission)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    bind_permissions int;
    user_role public.app_role;
BEGIN
    SELECT (auth.jwt() ->> 'user_role')::public.app_role INTO user_role;

    IF user_role IS NULL THEN
        RETURN false;
    END IF;

    SELECT count(*)
    INTO bind_permissions
    FROM public.role_permissions
    WHERE role_permissions.permission = requested_permission
      AND role_permissions.role = user_role;

    RETURN bind_permissions > 0;
END;
$$;


-- New-signup trigger: create profile row + grant default 'free' role.
-- ('free' = the no-cost tier; 'pro' is reserved for Phase 2 paid features.)
-- OAuth-aware: pulls display_name from user_meta.display_name (email signup) or
-- user_meta.full_name/name (Google), avatar_url from user_meta.avatar_url/picture.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    user_email      text;
    user_meta       jsonb;
    derived_name    text;
    derived_avatar  text;
BEGIN
    SELECT email, raw_user_meta_data
    INTO user_email, user_meta
    FROM auth.users
    WHERE id = NEW.id;

    derived_name := COALESCE(
        user_meta ->> 'display_name',
        user_meta ->> 'full_name',
        user_meta ->> 'name'
    );

    -- Fallback: extract prefix from email (before @) for email signups with no provider name.
    IF derived_name IS NULL AND user_email IS NOT NULL THEN
        derived_name := split_part(user_email, '@', 1);
    END IF;

    derived_avatar := COALESCE(
        user_meta ->> 'avatar_url',
        user_meta ->> 'picture'
    );

    INSERT INTO public.users (id, email, display_name, avatar_url, created_at, updated_at)
    VALUES (NEW.id, user_email, derived_name, derived_avatar, NOW(), NOW())
    ON CONFLICT (id) DO UPDATE SET
        email        = EXCLUDED.email,
        display_name = COALESCE(public.users.display_name, EXCLUDED.display_name),
        avatar_url   = COALESCE(public.users.avatar_url, EXCLUDED.avatar_url);

    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'free'::public.app_role)
    ON CONFLICT (user_id, role) DO NOTHING;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();


-- get_my_permissions(): returns the array of permissions for the current JWT's role.
-- Used by the client-side user store to populate userStore.permissions for hasPermission() checks.
CREATE OR REPLACE FUNCTION public.get_my_permissions()
RETURNS text[]
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    user_role public.app_role;
    perms text[];
BEGIN
    SELECT (auth.jwt() ->> 'user_role')::public.app_role INTO user_role;

    IF user_role IS NULL THEN
        RETURN ARRAY[]::text[];
    END IF;

    SELECT array_agg(permission::text)
    INTO perms
    FROM public.role_permissions
    WHERE role = user_role;

    RETURN COALESCE(perms, ARRAY[]::text[]);
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_my_permissions TO authenticated;


-- ────────────────────────────────────────────────────────────────────────────
-- MATCH / EVENT MUTATION POLICIES
-- ────────────────────────────────────────────────────────────────────────────
-- Final RLS state for matches/events (these depend on public.authorize() above).
-- Read policies live in the initial schema migration.

-- MATCHES --------------------------------------------------------------------

-- Authenticated owner inserts (with permission).
CREATE POLICY "matches_insert_owner" ON public.matches
    FOR INSERT TO authenticated
    WITH CHECK (
        owner_id = auth.uid()
        AND (SELECT public.authorize('match.create'))
    );

-- Authenticated users may also create anonymous matches (owner_id NULL — e.g. quick scrim).
CREATE POLICY "matches_insert_anon_authed" ON public.matches
    FOR INSERT TO authenticated
    WITH CHECK (owner_id IS NULL);

-- Anonymous users insert with owner_id NULL only.
CREATE POLICY "matches_insert_anon" ON public.matches
    FOR INSERT TO anon
    WITH CHECK (owner_id IS NULL);

-- Owner updates their match.
CREATE POLICY "matches_update_owner" ON public.matches
    FOR UPDATE TO authenticated
    USING (owner_id = auth.uid())
    WITH CHECK (
        owner_id = auth.uid()
        AND (SELECT public.authorize('match.update.own'))
    );

-- Authenticated users may update anonymous matches (e.g. signed in mid-match).
-- Permits claiming by setting owner_id = auth.uid() in the same UPDATE.
CREATE POLICY "matches_update_anon_authed" ON public.matches
    FOR UPDATE TO authenticated
    USING (owner_id IS NULL)
    WITH CHECK (owner_id IS NULL OR owner_id = auth.uid());

-- Anonymous users can update anonymous matches (URL = access token).
CREATE POLICY "matches_update_anon" ON public.matches
    FOR UPDATE TO anon
    USING (owner_id IS NULL)
    WITH CHECK (owner_id IS NULL);

-- Owner deletes their own match.
CREATE POLICY "matches_delete_owner" ON public.matches
    FOR DELETE TO authenticated
    USING (
        owner_id = auth.uid()
        AND (SELECT public.authorize('match.delete.own'))
    );


-- EVENTS ---------------------------------------------------------------------

-- Owner appends events to their match.
CREATE POLICY "events_insert_owner" ON public.events
    FOR INSERT TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.matches m
            WHERE m.id = events.match_id
              AND m.owner_id = auth.uid()
        )
        AND (SELECT public.authorize('match.update.own'))
    );

-- Anonymous and authenticated users append events to anonymous matches.
CREATE POLICY "events_insert_anon" ON public.events
    FOR INSERT TO anon
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.matches m
            WHERE m.id = events.match_id
              AND m.owner_id IS NULL
        )
    );

CREATE POLICY "events_insert_anon_authed" ON public.events
    FOR INSERT TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.matches m
            WHERE m.id = events.match_id
              AND m.owner_id IS NULL
        )
    );
